# Generated by Django 5.0.6 on 2024-06-22 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceLocation',
            fields=[
                ('label', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
