# Generated by Django 5.0.6 on 2024-06-22 04:34

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_policelocation_delete_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='policelocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
