# Generated by Django 5.0.6 on 2024-06-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mediafile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
