# Generated by Django 5.0.6 on 2024-06-25 04:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_city_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=core.models.upload_to),
        ),
    ]
